### ISSUE TITLE
No card for action

### ISSUE THREAD

**Issue by edtst** [MarvinSchenkel/HomeyKodi#1]
I have a Homey on 0.8.20 and I can use an action card. When I use homey on 0.8.22 There is no action card available.

EDIT: After fiddling around, it stopped working on 0.8.20 too. Reboots do not fix it.

**Comment by MarvinSchenkel** [comment]
Could you please describe the steps in detail  that introduced the problem, e.g. the action card you're using and the flow you have built.

**Comment by edtst** [comment]
Yes of course
1. Installed the app
2. went to flows
3. create a new flow
4. picked up the Kodi card 
5. dragged it to the THEN section
6. Card won't stick because it only shows the Kodi logo and will not turn into a card. 

Stupid me, I now see I have to create a kodi device and us ethen in teh THEN section. Sorry
