### ISSUE TITLE
Kodi 18 support

### ISSUE THREAD

**Issue by robertklep** [MarvinSchenkel/HomeyKodi#14]
I haven't yet tried myself, but according to [this forum post](https://community.athom.com/t/kodi-issue/1014), the app doesn't work properly with the Kodi 18 beta's.

**Comment by mighty2nyce** [comment]
I’m new to a lot of this and I been searching all day to try and get Kodi on my Apple TV 4 without going bad every 7 days. Can someone help me?

**Comment by robertklep** [comment]
@mighty2nyce is your problem related to the issue, or is it a more general question?

If the latter, I think the [Homey community forum](https://community.athom.com/) would be a better place to ask (if you post there, please elaborate on what "going bad" actually means).

**Comment by MarvinSchenkel** [comment]
This issue has been fixed in v2.2.1
