### ISSUE TITLE
Connection seems lost.

### ISSUE THREAD

**Issue by terryhendrix** [MarvinSchenkel/HomeyKodi#9]
The connection to my Kodi (on smart TV) gets lost every few days. It doesn't pickup any events from Kodi. The logs dont show the reconnect loop (still listeningForEvents), so i guess something weird is going on.

Maybe you can add a reconnect action to the app? (restarting the app always fixes my issue)

**Comment by MarvinSchenkel** [comment]
v2.2.0 has just been released with a huge rewrite. All connection issues should have been resolved.
